#A python program to understand list processing methods
num=[10,20,30,40,50]
n=len(num)
print('No.of elements in num:',n)
num.append(60)
print('num after appending 60:',num)
num1=num.copy()
print('Newly created list by using copy',num1)
num1.insert(0,5)
print('num after inserting 5 at position 0',num1)
num.extend(num1)
print('num after extending',num)
n=num.count(60)
print('counting how many times 60',n)
num.remove(50)
print('num',num)
num.pop()
print('after pop',num)
num.sort()
print('after sort',num)
num.reverse()
print('after reverse',num)
num.clear()
print('num after clearing',num)